docs/cryoet_data_portal_docsite_napari.md
The napari plugin is now available on PyPI: https://pypi.org/project/napari-cryoet-data-portal/
This updates the installation instructions accordingly.
=> Update napari plugin installation instructions

.github/workflows/deploy-to-dev.yml, .github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml, .github/workflows/staging-deploy.yml, frontend/.happy/config.json
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/51
Adds deployment to dev, staging, and prod environments.
=> Adding github workflows for deploy

frontend/packages/data-portal/app/components/BrowseData/DatasetKeyPhoto.tsx, frontend/packages/data-portal/app/components/Dataset/DatasetDescription.tsx, frontend/packages/data-portal/app/components/Dataset/DatasetHeader.tsx
Implemented as in #31. Adds the dataset level key photo. Note: actual key photo not available from database yet. Contains CSS code which does not run on IE (which when synced with @codemonkey800 is not a browser we support anyways).
https://github.com/chanzuckerberg/cryoet-data-portal/assets/29165011/fc18e9c5-4e2a-4732-8bb7-11217ea6e33e
=> add single dataset key photo

frontend/packages/data-portal/app/components/Layout/ToolsDropdown.tsx
The link to the API was incorrectly labeled as "FAQ"; this PR fixes that and should resolve https://github.com/chanzuckerberg/cryoet-data-portal/issues/151.  (The correct FAQ is linked under the "About & Help" section).
=> Fix naming from FAQ to API

frontend/packages/data-portal/app/components/Download/AWSDownloadTab.tsx
Adds `--no-sign-request` flag so that AWS does not attempt to load credentials, as intended in https://github.com/chanzuckerberg/cryoet-data-portal/issues/59#issuecomment-1796480671.  Also adds a destination folder. 
Otherwise, the command fails with `fatal error: Unable to locate credentials`
**Note: This will still not work against staging due to permissions, but will work on the prod site.**
=> Update AWS download command

frontend/packages/data-portal/app/components/DatasetFilter/IncludedContentsFilterSection.tsx
Removing `Tomogram` from the Available Files filters (as at least a stopgap) due to the query timing out.
=> Remove 'Tomogram' from Available Files filter

.github/workflows/dev-deploy.yml
Closes https://github.com/chanzuckerberg/cryoet-data-portal/issues/325
The cluster uses an image if it already exists in the machine. Using the stack name as the tag causes it to use the old image even if a new image is available, as there is no difference in their tags. Removing the explicit static tag makes happy default to the github sha as a tag. This will fix the caching issue.
=> Removing stack name as tag

frontend/packages/data-portal/app/routes/browse-data.datasets.tsx, frontend/packages/data-portal/app/routes/datasets.$id.tsx, frontend/packages/data-portal/app/routes/runs.$id.tsx
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/310
Removing the `distinct_on` constraint on the name, as it sorts by name first and then the other sorting fields. This results in the `author_list_order` sorting being ignored.
=> Removing ordering author by name

frontend/packages/data-portal/app/components/DatasetFilter/AnnotationMetadataFilterSection.tsx, frontend/packages/data-portal/app/components/TablePageLayout.tsx, frontend/packages/data-portal/app/hooks/useDatasetFilter.ts
fixes side-effect of #303 in which if a page was selected that was invalid due to exceeding the items in the filter, no results are displayed
preview at https://dev-kira-pagination.cryoet.dev.si.czi.technology/browse-data/datasets
https://github.com/chanzuckerberg/cryoet-data-portal/assets/29165011/78494a84-92fa-40b9-8a0d-9f695594934c
=> reset page to 1 if page exceeds pages in filtered results

.github/workflows/dev-deploy.yml
Reduces the max limit for a stack name to 25 characters. 
Stack name of length longer than 25 creates aws resources of length longer than limit of 64, this cause the deploy to fail.
=> Updating dev stack name limit

frontend/packages/data-portal/app/components/DatabaseEntry.tsx, frontend/packages/data-portal/app/components/Dataset/DatasetMetadataTable.tsx, frontend/packages/data-portal/app/components/Dataset/SampleAndExperimentConditionsTable.tsx, frontend/packages/data-portal/app/constants/datasetInfoLinks.ts, frontend/packages/data-portal/app/routes/datasets.$id.tsx, frontend/packages/data-portal/app/routes/runs.$id.tsx, frontend/packages/data-portal/public/locales/en/translation.json
fixes #249, #244, #150
preview @ https://dev-kira-1.cryoet.dev.si.czi.technology/
=> fix single dataset visual bugs

frontend/packages/data-portal/app/components/Run/RunHeader.tsx
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/394
Updates `sampling available` value to be updated from existing field in the query [here](https://github.com/chanzuckerberg/cryoet-data-portal/blob/498e4e02af55e01e9a3d70eca625931d19977eee/frontend/packages/data-portal/app/graphql/getRunById.server.ts#L182).
Demo:
=> fix: Mapping samplings available to db field

docs/cryoet_data_portal_docsite_examples.md, docs/cryoet_data_portal_docsite_quick_start.md
Apart from some small typos and such, a meaningful change is removing a mention of scaling in one of the quick start examples, since tomograms are not binned any more (noticed during a meeting with Utz).
The updated wording doesn't get into details, but I had two questions:
- Are the tomograms that will get downloaded the highest *available* resolution, but not necessarily the maximum *possible* resolution? Answer: Yes.
- When the code iterates over all tomograms, are they unique, or can there be different resolutions of the same tomogram? Answer: There can be, but there are none right now.
=> docs: Minor updates to documentation site

client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py, client/python/cryoet_data_portal/src/cryoet_data_portal/data/schema.graphql, client/python/cryoet_data_portal/tests/test_infra/hasura/metadata/databases/cryoetdataportal/tables/public_annotation_files.yaml, client/python/cryoet_data_portal/tests/test_infra/hasura/metadata/databases/cryoetdataportal/tables/public_annotations.yaml, client/python/cryoet_data_portal/tests/test_infra/hasura/metadata/databases/cryoetdataportal/tables/public_tomograms.yaml, client/python/cryoet_data_portal/tests/test_infra/hasura/migrations/cryoetdataportal/1706552817192_alter_annotation_add_tomogram_table/up.sql
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/601, https://github.com/chanzuckerberg/cryoet-data-portal/issues/443, https://github.com/chanzuckerberg/cryoet-data-portal/issues/632 
1. Adds deposition_id field to Tomogram and Annotation models
2. Adds method_type field to Annotation model
3. Updates documentation of Annotation model to include relationship to AnnotationFiles
=> chore: Updating client for new db fields

client/python/cryoet_data_portal/src/cryoet_data_portal/_gql_base.py, client/python/cryoet_data_portal/tests/test_filters.py
Fix for #626 , raise an exception when filtering on invalid fields.
=> fix: Raise exception when attempting to filter on related objects.

frontend/packages/data-portal/app/graphql/getBrowseDatasets.server.ts, frontend/packages/data-portal/app/hooks/useDatasets.ts
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/660
- Optimizes by removing the join for fetching annotation shape types.
=> fix: Updating annotation object shape type query

frontend/.happy/terraform/envs/dev/main.tf, frontend/.happy/terraform/envs/prod/main.tf, frontend/.happy/terraform/envs/staging/main.tf
Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/662
- Updating the happy-stack-eks reference to the current latest version as the referenced branch no longer exists. 
- Adding explicit values for the liveliness_timeout and readiness_timeout to help the `Client.Timeout exceeded while awaiting headers` errors.
=> fix: Adding liveliness_timeout and readiness_timeout 

client/python/cryoet_data_portal/pyproject.toml, client/python/cryoet_data_portal/src/cryoet_data_portal/_gql_base.py, client/python/cryoet_data_portal/tests/test_filters.py
Using ```somedict.update()``` to merge filters was overwriting deeply nested filters instead of combining them. The `deepmerge` library can merge nested structures better.
=> fix: Merge query filters properly

frontend/packages/data-portal/e2e/metadataDrawer/testMetadataDrawer.ts, frontend/packages/eslint-config/typescript.cjs
The new `runId` shows "Not Applicable" for some metadata fields instead of "--".
Also add a lint exception to allow `continue` (I believe it's the Airbnb plugin that's disallowing it, but supposedly their company also disallows loops entirely...) since in this case it reduced nesting, but lmk if we want to keep it banned.
=> chore: Fix metadata test

frontend/packages/data-portal/app/i18n.ts, frontend/packages/data-portal/e2e/browseDatasetFilter.test.ts, frontend/packages/data-portal/public/locales/en/translation.json
Resolves #802 
Change Empiar to EMPIAR because this is an acronym.
=> fix: change Empiar to EMPIAR

frontend/packages/data-portal/app/constants/table.ts
Resolves #686 
The column width seems to be responsive based on the cell content rather than the header content.  To combat this, this PR sets a min width on the Tilt Series Quality Score to ensure the header displays.  It's unclear to me whether setting a larger minimum value will have negative impacts on making the table responsive (is that a priority?).  The responsive issue would apply to all of the columns, so this change likely doesn't make anything worse.
=> fix: Increase width for tilt series quality score column.

frontend/packages/data-portal/app/components/AnnotatedObjectsList.tsx, frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx, frontend/packages/data-portal/app/components/RunFilter/RunFilter.tsx, frontend/packages/data-portal/e2e/singleDatasetFilter.test.ts, frontend/packages/data-portal/public/locales/en/translation.json
Resolves #603 
Resolves #860 
We were capitalizing the annotation object names.  Now we're not.
The annotation filter should say "Object Name" rather than "Annotated Object Name"
=> fix: stop capitalizing annotation object display

frontend/packages/data-portal/app/components/Filters/Filters.module.css, frontend/packages/data-portal/app/components/InlineMetadata.tsx
https://github.com/chanzuckerberg/cryoet-data-portal/issues/864
- Makes non-uppercase `<InlineMetadata>`s not use caps style.
- Makes ground truth filter text style match that of other filters.
=> fix: CSS tweaks to labels

docs/cryoet_data_portal_docsite_data.md
The '&' in the link wasn't escaped. I randomly tried something, and it seemed to work in the preview, but please check it out if it's the right thing to do!
=> docs: Fix contribution form link in Data Organization page

frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx, frontend/packages/data-portal/app/graphql/getRunById.server.ts
Resolves #891 
In order to display a separate annotation row for each shape type, we expand the list of annotations on the frontend.  This adds a check to the expansion function for whether the shape type is filtered out.
=> fix: Don't add annotation rows for shape types that are filtered out

docs/cryoet_data_portal_docsite_data.md
I was reading the section and thought of some clarifications, for example: there's no "Download Run" button, but a "Download ..." button. Feel free to consider these as suggestions and tweak as appropriate!
=> docs: Clarifications in Run Download Options section

client/python/cryoet_data_portal/tests/test_filters.py, client/python/cryoet_data_portal/tests/test_infra/.gitignore
The `test_filter_on_object_raises_exceptions` test previously checked for an exception to have an exact test message. The schema must have changed a little since these were first written, so now these tests fail.
Instead of trying to match the whole string and updating it every time the schema changes, I used the `match` keyword to match a common substring that should be more stable.
I also ignored a small test file that's created as part of the test setup.
=> fix: Use match with substring for exception check in client tests

frontend/packages/data-portal/app/components/TablePageLayout.tsx, frontend/packages/data-portal/app/components/Tabs.tsx, frontend/packages/data-portal/app/constants/query.ts, frontend/packages/data-portal/app/graphql/getRunById.server.ts, frontend/packages/data-portal/app/routes/browse-data.datasets.tsx, frontend/packages/data-portal/app/routes/browse-data.depositions.tsx, frontend/packages/data-portal/app/routes/datasets.$id.tsx, frontend/packages/data-portal/app/routes/runs.$id.tsx, frontend/packages/data-portal/e2e/dialogs/singleRun.ts, frontend/packages/data-portal/e2e/filters/utils.ts, frontend/packages/data-portal/e2e/pageObjects/filters/filtersActor.ts, frontend/packages/data-portal/e2e/pageObjects/filters/utils.ts, frontend/packages/data-portal/e2e/pageObjects/metadataDrawer/utils.ts, frontend/packages/eslint-config/typescript.cjs
This is to support having both Annotations and Tomograms tabs on the Runs page.
- Adds support for a header above the tabs.
- Uses our existing `<Tabs>` component.
- Only shows tabs if more than 1 is specified.
- Supports a different pagination query param per tab.
- This changes the query param on the Runs page from `page` to `annotations-page`. In a subsequent PR I'll add `tomograms-page`. 
- It seems like we're currently pretty far from either annotations or tomograms getting to a point where they'd actually trigger pagination, but I'd prefer this to work properly from the get-go rather than find out there's a bug later.
- Stores the currently open tab in URL params.
- Make a few prop names clearer.
- Allow `<Tabs>` to take in components as labels and `number`s (i.e. indexes) as …
=> feat: Refactor <TablePageLayout> to support multiple tabs

.github/workflows/client-python.yml
- add argument to fail loudly if codecoverage upload fails
There is a separate ticket to fix the failure https://github.com/chanzuckerberg/cryoet-data-portal/issues/945
=> chore: codecov failure should fail loudly

frontend/packages/data-portal/app/components/Breadcrumbs.tsx
Resolves #814 
~This manually unencodes the space character and replaces `%20` with `+`.  It uses `encodeURIComponent`, but no longer uses the `URLSearchParams` object.  This was necessary to avoid re-encoding the `+` character.  It works, but the approach seems a bit hacky.~
Now just removing the encoding and it works.
=> fix: avoid double-encoding spaces in breadcrumb url

client/python/cryoet_data_portal/src/cryoet_data_portal/__init__.py, client/python/cryoet_data_portal/src/cryoet_data_portal/_client.py, client/python/cryoet_data_portal/src/cryoet_data_portal/_constants.py, client/python/cryoet_data_portal/src/cryoet_data_portal/_file_tools.py, client/python/cryoet_data_portal/src/cryoet_data_portal/_version.py
- To make identifying the user agent who made a request to s3 or the portal backend easier to identify.
- #522 
- Move __version__ to _version.py so it can be used in USER_AGENT. 
- Add _constants.py to store the USER_AGENT use in boto3 and http requests
- Add python version, and cryoet-data-portal client version to USER_AGENT.
=> feat: add user agent to client requests

frontend/packages/data-portal/app/components/TablePageLayout.tsx, frontend/packages/data-portal/app/constants/query.ts, frontend/packages/data-portal/app/routes/runs.$id.tsx, frontend/packages/data-portal/public/locales/en/translation.json
#624 
Adds basic tabs functionality (UX not final).
Currently the Tomograms tab just shows the Annotations table with no filters.
Next: Add initial Tomograms table.
https://github.com/user-attachments/assets/cb54c5b1-e4a3-40a4-a4ac-40f072a06e11
=> feat: Add Tomograms tab to Run page

frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx, frontend/packages/data-portal/app/context/DownloadModal.context.ts, frontend/packages/data-portal/app/graphql/getRunById.server.ts, frontend/packages/data-portal/app/hooks/useRunById.ts, frontend/packages/data-portal/app/routes/runs.$id.tsx, frontend/packages/data-portal/app/state/annotation.ts, frontend/packages/data-portal/app/utils/annotation.ts, frontend/packages/data-portal/e2e/filters/utils.ts, frontend/packages/data-portal/e2e/pageObjects/filters/utils.ts, frontend/packages/data-portal/e2e/pageObjects/metadataDrawer/utils.ts, frontend/packages/eslint-config/typescript.cjs
#581 
This changes the Annotations table GQL to query annotation_files at the top level instead of annotations.
Because `distinct_on` was not able to be used to generate distinct `annotation` and `shape_type` pairs (see comments in issue), this instead ignores .zarr files for the time being to make each `annotation_file`'s `shape_type` within an `annotation` unique.
=> feat: Enable pagination of Annotations table with temporary hacky query

.github/workflows/frontend-pr-e2e-tests.yml, frontend/packages/data-portal/e2e/pageObjects/neuroglancerPage.ts, frontend/packages/data-portal/e2e/pageObjects/singleRunPage.ts, frontend/packages/data-portal/e2e/singleRun.test.ts, frontend/packages/data-portal/playwright.config.ts
#1025
Had to add some startup flags to chromium so that WebGL is enabled (and the Neuroglancer site actually loads).
Tried with firefox and webkit as well and both worked without any extra flags.
=> chore: Add e2e test for errors on Neuroglancer site

frontend/packages/data-portal/app/components/DatasetFilter/AnnotationMetadataFilterSection.tsx, frontend/packages/data-portal/app/components/DatasetFilter/DatasetFilter.tsx, frontend/packages/data-portal/app/components/DatasetFilter/HardwareFilterSection.tsx, frontend/packages/data-portal/app/components/DatasetFilter/IncludedContentsFilterSection.tsx, frontend/packages/data-portal/app/components/DatasetFilter/SampleAndExperimentFilterSection.tsx, frontend/packages/data-portal/app/components/DatasetFilter/TomogramMetadataFilterSection.tsx, frontend/packages/data-portal/app/components/Filters/BooleanFilter.tsx, frontend/packages/data-portal/app/components/Filters/GroundTruthAnnotationFilter.tsx, frontend/packages/data-portal/app/components/Filters/SelectFilter.tsx, frontend/packages/data-portal/app/graphql/getBrowseDatasets.server.ts, frontend/packages/data-portal/app/graphql/getDatasetsFilterData.server.ts, frontend/packages/data-portal/app/hooks/useDatasets.ts, frontend/packages/data-portal/app/hooks/useDatasetsFilterData.ts, frontend/packages/data-portal/app/hooks/useDepositionById.ts, frontend/packages/data-portal/app/routes/browse-data.datasets.tsx, frontend/packages/data-portal/app/routes/depositions.$id.tsx, frontend/packages/data-portal/e2e/pageObjects/filters/filtersActor.ts, frontend/packages/data-portal/e2e/pageObjects/filters/utils.ts, frontend/packages/data-portal/public/locales/en/translation.json
#923 
note that applying filters will not filter the results until #920 and will merely update the search params
=> feat: add filter panel to single deposition page

frontend/packages/data-portal/app/components/Download/ConfigureTomogramDownloadContent.tsx, frontend/packages/data-portal/app/components/Download/DownloadOptionsContent.tsx, frontend/packages/data-portal/app/components/Run/RunHeader.tsx, frontend/packages/data-portal/app/context/DownloadModal.context.ts, frontend/packages/data-portal/app/graphql/getRunById.server.ts, frontend/packages/data-portal/app/hooks/useRunById.ts, frontend/packages/data-portal/app/routes/runs.$id.tsx, frontend/packages/data-portal/app/utils/nullish.ts, frontend/packages/data-portal/e2e/pageObjects/downloadDialog/utils.ts, frontend/packages/data-portal/e2e/singleRun.test.ts
#993 
- `object_name` and `annotation_software` are now distinct in the GQL response.
- `object_shape` is now guaranteed distinct across `tomogram_voxel_spacings` in the GQL response.
- The `tomogram`s query used for downloads is now separate from the query for distinct `voxel_spacing`s.
=> feat: Fix/clean up tomogram_stats query

frontend/packages/data-portal/app/components/CollapsibleList.tsx
fix alignment of show more/less button when collapsible list is in a grid
=> fix: wrap collapsible lists in a div

client/python/cryoet_data_portal/Makefile, client/python/cryoet_data_portal/tests/docker-compose.yml
The existing `test-infra` make target calls `docker compose up` to set up the various services needed for the Python client tests to run successfully. This change forces `docker compose up` to wait until the `graphql-engine` service is healthy before it exits. I borrowed the healthcheck test from another similar docker compose service in this and the corresponding backend repo.
I added a wait timeout so that our runners cannot hang indefinitely on this step. The [`docker compose up` docs](https://docs.docker.com/reference/cli/docker/compose/up/) are not totally clear, but I assume `--wait-timeout` is specified in seconds because `--timeout` is specified as such. I chose 300 seconds because this step takes about 30 seconds on my fairly speedy laptop, so multiplying by 10 for a random …
=> fix: wait for graphql to be healthy in client tests

client/python/cryoet_data_portal/Makefile, client/python/cryoet_data_portal/release_process.md
adding manual steps to release due to https://github.com/chanzuckerberg/cryoet-data-portal/issues/1072
=> chore: add instructions and commands to manually release the python package.

frontend/packages/data-portal/app/components/Run/AnnotationObjectTable/components/ObjectIdLink/ObjectIdLink.tsx, frontend/packages/data-portal/app/constants/annotationObjectIdLinks.ts
A patch to a recently merged PR (#1068) Some small changes were not properly committed and I missed that.
=> fix: ID detection for annotation object id link 

frontend/packages/data-portal/app/components/Dataset/DatasetHeader.tsx, frontend/packages/data-portal/app/components/HeaderKeyPhoto.tsx, frontend/packages/data-portal/app/components/PageHeader.tsx, frontend/packages/data-portal/app/components/Run/RunHeader.tsx
#1047
- Fixes extra padding in header.
- Adds ability to click dataset image (like run image).
=> feat: Make main photo HTML and CSS consistent between run and dataset pages

frontend/packages/data-portal/app/components/BrowseData/DatasetTable.tsx, frontend/pnpm-lock.yaml
This PR carries over filter query params between the browse datasets page and single dataset page.  The carry over between the dataset page and run page was already implemented.
=> fix: Carry over filters from datasets table

frontend/packages/data-portal/e2e/pagination.test.ts, frontend/packages/data-portal/e2e/pagination/testPagination.ts
Relates to #963 
We decided to deprioritize refactoring the pagination tests since we do not anticipate needing updates soon.  This PR adds a comment to the two pagination related test files indicating that future devs should follow the page object model instead.
=> chore: Leave comments about not refactoring pagination tests

frontend/packages/data-portal/app/components/AnnotationFilter/ObjectIdFilter.tsx, frontend/packages/data-portal/app/components/DepositionFilter/DepositionIdFilter.tsx, frontend/packages/data-portal/app/components/Filters/DropdownFilterButton.tsx, frontend/packages/data-portal/app/components/Filters/EntityIdFilter.tsx, frontend/packages/data-portal/app/components/Filters/MultiInputFilter.tsx, frontend/packages/data-portal/app/components/Filters/RegexFilter.tsx, frontend/packages/data-portal/app/components/Filters/utils.ts, frontend/packages/data-portal/app/constants/idPrefixes.ts, frontend/packages/data-portal/app/utils/idPrefixes.test.ts, frontend/packages/data-portal/app/utils/idPrefixes.ts, frontend/packages/data-portal/e2e/browseDatasetFilters.test.ts, frontend/packages/data-portal/e2e/pageObjects/filters/utils.ts, frontend/packages/data-portal/e2e/singleDatasetFilters.test.ts, frontend/packages/data-portal/e2e/singleRunFilters.test.ts
Issue #1015 
When filtering by an id, do not include the prefix in the url query params.  Do include the prefix in the display chip for active filters.
Note: Does this need to be behind a feature flag?
=> feat: Id prefixes in filters

frontend/packages/data-portal/app/components/HeaderKeyPhoto.tsx, frontend/packages/data-portal/app/components/Run/RunHeader.tsx
fix misc sizing issues for header key photos across various pages
https://github.com/user-attachments/assets/cc7ce779-c1f8-45c9-842c-0182f4834a74
https://github.com/user-attachments/assets/ba9b89a7-81f1-4282-980a-f8ec6a10f6c3
=> fix: header key photo sizing

frontend/packages/data-portal/app/components/HeaderKeyPhoto.tsx
I'm not sure why the `max-h-[330px]` was there before, but `<KeyPhoto>` already controls the sizing and aspect ratio stuff so `max-w` should be enough...
Before: 
After:
=> fix: Fix not enough padding below key photos

frontend/packages/data-portal/app/components/Run/AnnotationOveriewTable.tsx, frontend/packages/data-portal/public/locales/en/translation.json
=> feat: Add alignment ID row + tooltip

docs/_static/css/custom.css
Makes attributes list more compact.
To see how this looks, go to https://melissawm.github.io/cryoet-data-portal/python-api.html
=> docs: Better display of attributes in API

frontend/packages/data-portal/app/components/Dataset/RunsTable.tsx, frontend/packages/data-portal/app/components/Run/RunHeader.tsx, frontend/packages/data-portal/app/components/Run/TomogramTable.tsx, frontend/packages/data-portal/app/constants/table.ts
closes #1095 
Now that we've upgraded to the latest SDS icon set!
=> feat: Update view tomogram button icons

frontend/packages/data-portal/app/components/Run/TomogramMetadataDrawer.tsx, frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts, frontend/packages/data-portal/e2e/pageObjects/metadataDrawer/utils.ts
The field name has changed to `title`. Don't query `title` yet because that change has not made it into APIv2 prod.
=> fix: Stop querying depositionTitle

docs/_static/css/custom.css, docs/_static/js/faq.js, docs/conf.py, docs/cryoet_data_portal_docsite_faq.md
Fixes display of the FAQ items to match what is currently on the Data Portal site (respecting SDS) and also implements a javascript function to allow links to open accordions with a URL attribute.
If the FAQ item has the property `:name: submit-issue`, then the following url would link to this specific item, and open the accordion to the answer:
`https://chanzuckerberg.github.io/cryoet-data-portal/cryoet_data_portal_docsite_faq.html?target=submit-issue&status=open`
I am happy to revisit in case there are better ways of doing this.
Closes #772
=> docs: Fix docs site FAQ display and linking

frontend/packages/data-portal/app/components/Download/ConfigureTomogramDownloadContent.tsx, frontend/packages/data-portal/app/components/Download/Tomogram/TomogramSelector.tsx, frontend/packages/data-portal/app/components/Download/Tomogram/TomogramSelectorLabel.tsx, frontend/packages/data-portal/app/components/Download/Tomogram/TomogramSelectorOption.tsx, frontend/packages/data-portal/app/components/TomogramTypeBadge.tsx
#1005
The messed up paddings are tracked in #1158
=> feat: Add standard tomogram badge to tomogram selector

frontend/packages/data-portal/app/components/Download/AnnotationAlignmentCallout.tsx, frontend/packages/data-portal/app/components/Download/ConfigureAnnotationDownloadContent.tsx, frontend/packages/data-portal/app/components/Download/DownloadOptionsContent.tsx, frontend/packages/data-portal/e2e/pageObjects/downloadDialog/types.ts, frontend/packages/data-portal/public/locales/en/translation.json
#1046
Transforming annotations is now out of scope.
Alignment of annotation has not been integrated with the BE yet, since that requires migrating the entire annotations query.
=> feat: Undo changes for transforming annotations and add new callout for mismatched alignments

frontend/packages/data-portal/app/apiNormalization/browseAllDepositionsV1.ts, frontend/packages/data-portal/app/apiNormalization/browseAllDepositionsV2.ts, frontend/packages/data-portal/app/apiNormalization/index.ts, frontend/packages/data-portal/app/components/BrowseData/DepositionTable.tsx, frontend/packages/data-portal/app/graphql/getBrowseDepositions.server.ts, frontend/packages/data-portal/app/graphql/getBrowseDepositionsV2.server.ts, frontend/packages/data-portal/app/hooks/useDepositions.ts, frontend/packages/data-portal/app/routes/browse-data.depositions.tsx, frontend/packages/data-portal/app/types/PageData/browseAllDepositionsPageData.ts, frontend/packages/data-portal/app/types/authorInfo.ts, frontend/packages/data-portal/e2e/apiLoaders/browseAllDepositions.ts, frontend/packages/data-portal/e2e/apiMigration.test.ts
#1229 
#1227
note that there is no way from my current knowledge to get distinct values from `depositions.shapeTypes` in the V2 API which hinders performance so it fetches from V1 instead for ~33% faster load times
=> feat: api migration for browse all depositions page

client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py, client/python/cryoet_data_portal/src/cryoet_data_portal/templates/Header.jinja2, client/python/cryoet_data_portal/src/cryoet_data_portal/templates/Model.jinja2, client/python/cryoet_data_portal/tests/test_get_by_id.py
Fix: #1379 
We broke the interface for `get_by_id` when improving the generated documentation for the client. This fixes the interface and adds a test.
=> fix: fix argument and return value handling for get_by_id

frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts, frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
Don't need to query `id` from `methodLinks`.
=> fix: Fix more run page diff logs

frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
Turns out the braces format was a BE bug.
=> fix: Fix affine transformation matrix diff log

frontend/packages/data-portal/app/hooks/useRunById.ts
There's a bunch of existing nullish handling logic that I decided to keep around for now, even though all these fields should be defined under normal circumstances.
=> feat: Use V2 aggregate data in run page

frontend/packages/data-portal/app/routes/depositions.$id.tsx
Forgot to update the variable name for the deposition page which also uses the filter data query. I only changed the variable name in the hook and in the datasets page loader.
=> fix: Fix deposition dropdown filters being broken

frontend/packages/data-portal/app/graphql/getDatasetByIdV2.server.ts, frontend/packages/data-portal/app/graphql/getDatasetsV2.server.ts, frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts, frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
- Undoes the refactoring that initializes empty objects by default because apparently sending empty argument objects to Platformics does affect query results 🫢 
- I went with using `??=` to initialize empty objects only when needed. It's a bit more annoying to look at but compared to initializing empty objects in a separate if condition (what I had before) it prevents the need to use non-null assertions everywhere and makes it obvious that the object is being correctly initialized at first glance without having to check that the if conditions align.
=> fix: Never send empty argument objects to APIv2

frontend/packages/data-portal/app/hooks/useDatasetById.ts
Since I found out sometimes the `aggregate` array is actually empty in Platformics, I realized it's probably better to just not make any non-null assumptions about Platformics responses anymore.
=> fix: Remove non-null assertions in dataset page hook

frontend/packages/data-portal/app/graphql/fragments/getDatasetsFilterValuesV2.server.ts, frontend/packages/data-portal/app/graphql/getDatasetsV2.server.ts
- Adds more shared fields into the fragment.
- Stops sending empty argument objects when there is no `deposition` ID, based on previous findings that sending empty objects is not a no-op.
=> chore: Refactor datasets filter values fragment

docs/cryoet_data_portal_docsite_faq.md
Closes #1386 
On hover, each FAQ question will show a special character with tooltip "Permalink to this question". When clicked, or right-clicked and copied, this link will lead to this specific question in the FAQ page, with the accordion opened.
=> docs: Add anchors to FAQ questions

frontend/packages/data-portal/app/graphql/common.ts, frontend/packages/data-portal/app/graphql/fragments/getDatasetsAggregatesV2.server.ts, frontend/packages/data-portal/app/graphql/getDatasetsV2.server.ts, frontend/packages/data-portal/app/graphql/getDepositionById.server.ts, frontend/packages/data-portal/app/graphql/getDepositionByIdV2.server.ts, frontend/packages/data-portal/app/hooks/useDepositionById.ts, frontend/packages/data-portal/app/routes/depositions.$id.tsx
Sends the new query to the BE but doesn't use any of the data yet.
Also factors filter logic for deposition and datasets pages into common function.
Also fixes bugs:
- V1 query distinct object names per dataset weren't filtered by the deposition.
- Changes to sort query param weren't refreshing Remix loader.
=> feat: Convert deposition page query to V2

frontend/packages/data-portal/app/graphql/getDatasetsDiffer.ts, frontend/packages/data-portal/app/graphql/getDepositionByIdV2.server.ts, frontend/packages/data-portal/app/graphql/getDepositionDiffer.ts, frontend/packages/data-portal/app/routes/depositions.$id.tsx
Lot of it is very similar to the diff logger for datasets page.
Removes hack from datasets diff logger (bug now fixed).
Removes `annotationSoftware` and `datasetPublications` from the query (not used anywhere).
Split the annotation methods fields into 2 (1 for the aggregates per `annotation_method`, 1 for the combination of all `annotation_method`s and `method_links`).
=> feat: Diff logging for deposition page

frontend/packages/data-portal/app/hooks/useDatasetsFilterData.ts
=> feat: Migrate datasets and deposition filter values to use V2 data

frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
For some reason, `null`s in `annotationAuthors` were converted to `False` in V2, but not any of the other author objects...
=> fix: Convert null to false for annotation authors in run page differ

.github/workflows/frontend-e2e-tests.yml, frontend/packages/data-portal/app/components/Deposition/MethodLinks/common.tsx
Tests action started refusing to run.
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
=> chore: Upgrade upload-artifact

frontend/.happy/terraform/envs/staging/main.tf
Relates to [#1531](https://github.com/chanzuckerberg/cryoet-data-portal/issues/1531)
Updates the image_pull_policy in staging "IfNotPresent"->"Always".
=> fix: Update staging image_pull_policy

frontend/packages/data-portal/e2e/apiMigration.test.ts, frontend/packages/data-portal/e2e/metadataDrawer.test.ts
Temporarily disable this so that we can test running the prod deploy directly from the main branch.
This is an attempt to fix the issue of prod pods not properly deploying.
=> feat: Disable API migration test

frontend/packages/data-portal/app/graphql/common.ts, frontend/packages/data-portal/app/graphql/getDatasetByIdDiffer.ts, frontend/packages/data-portal/app/graphql/getDatasetsDiffer.ts, frontend/packages/data-portal/app/graphql/getDepositionDiffer.ts, frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
Due to reenabling `__typename` in a previous PR.
=> fix: Ignore __typename in diff logs

frontend/packages/data-portal/app/hooks/useDepositionById.ts
=> feat: Stop using V1 annotation method counts query in deposition page, switch to main deposition V2 query

frontend/packages/data-portal/app/components/Deposition/AnnotationsSummaryMetadataTable.tsx, frontend/packages/data-portal/app/constants/objectShapeTypes.ts, frontend/packages/data-portal/app/graphql/getDepositionByIdV2.server.ts, frontend/packages/data-portal/app/graphql/getDepositionDiffer.ts, frontend/packages/data-portal/app/hooks/useDatasets.ts, frontend/packages/data-portal/app/hooks/useDatasetsFilterData.ts, frontend/packages/data-portal/app/hooks/useDepositionById.ts, frontend/packages/data-portal/app/routes/browse-data.datasets.tsx, frontend/packages/data-portal/app/routes/depositions.$id.tsx, frontend/packages/data-portal/public/locales/en/translation.json
#1228 #1230
- Switches all relevant code to use new V2 `DatasetsAggregates` fragment.
- Removes some fields from the main deposition query that were already covered by the fragment.
- Fix bug where total dataset count was querying for datasets with the deposition ID rather than datasets with annotations with the deposition ID.
- This temporarily puts the data in the deposition page in an inconsistent state when using annotation filters, because the table is still using V1 whose query is technically wrong (it allows datasets that have annotations belonging to the deposition and any other annotation matching the annotation filter, rather than datasets that have annotations that both belong to the dataset and the annotation filter).
=> feat: Finish migrating deposition and datasets aggregates to use V2

frontend/packages/data-portal/app/components/Deposition/DatasetsTable.tsx, frontend/packages/data-portal/app/hooks/useDepositionById.ts, frontend/packages/data-portal/app/types/gql/depositionPageTypes.ts
=> feat: Convert deposition page datasets table to use V2 data

docs/conf.py
I didn't realize the version number and aliases should be switched in conf.py. This is not urgent but should fix future builds.
Follow-up to #1558
=> fix: Stable version redirect

.github/workflows/prod-deploy.yml, frontend/packages/data-portal/e2e/browseDatasetFilters.test.ts
Some tests are going to fail due to the migration because V1 data (and sometimes V1 queries) don't match with V2 all the time. It's going to take considerable effort to migrate the tests over. Also doing prod deploys off the branch was causing issues so we need to get main working again for prod deploys to resume.
=> chore: Skip failing test

frontend/packages/data-portal/app/root.tsx
I noticed that though the CSS said that Inter was the intended font it was not loaded. It does change the look and feel of the site a bit so I wanted give folks a heads up. 
In this PR:
Add Inter font in header
=> fix: Update font to intended Inter font

frontend/packages/data-portal/app/hooks/useDepositions.ts, frontend/packages/data-portal/app/routes/browse-data.datasets.tsx, frontend/packages/data-portal/app/routes/browse-data.depositions.tsx, frontend/packages/data-portal/app/routes/datasets.$id.tsx, frontend/packages/data-portal/app/routes/depositions.$id.tsx, frontend/packages/data-portal/app/routes/runs.$id.tsx
closes #1547
Not trying to change the shape of the object returning by the loader too much because there's a bug where if the loader return value changes in a non-backwards-compatible way, the app will be broken for a short period of time (?). Hopefully someone can figure that out and then update the loaders to remove the `v2` properties.
Not deleting the differs so we can still reference them while migrating the tests.
=> feat: Stop querying V1

frontend/packages/data-portal/app/components/Download/AWSDownloadTab.tsx, frontend/packages/data-portal/e2e/pageObjects/downloadDialog/downloadDialogActor.ts
Related to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/1578
Update the All Annotations AWS CLI command snippet to iterate over all `VoxelSpacing` folders for annotations:
=> fix: All Annotations AWS CLI command

.github/workflows/frontend-e2e-tests.yml, .github/workflows/prod-deploy.yml
Also improve Slack message to only send if the prod deploy action actually ran.
=> fix: Disable firefox and webkit e2e tests during prod deploy

.github/workflows/frontend-e2e-tests.yml, .github/workflows/frontend-pr-e2e-tests.yml
closes #1608 
I think this is necessary because of https://www.chromatic.com/docs/branching-and-baselines/#how-is-merge-base-calculated:~:text=The%20baseline%20is%20the%20last%20accepted%20snapshot%20on%20a%20given%20branch?
Seems like accepting new baselines on PRs only associates the new baselines with the PR's branch? So the action has to run again on `main` for the new baseline to be updated for future runs?
=> fix: Auto accept Chromatic baseline changes to main

frontend/packages/data-portal/app/components/AuthorLegend.tsx
It looks like the regular [SDS tooltip width is limited to 250px, but there is a wide option](https://sds.czi.design/009eaf17b/p/74af45-tooltips/t/page-74af45-76022550-3989d2-6) which is what I'm adding here.
Closes #1650
=> fix: Make authors tooltip fit content properly

docs/_templates/base.html, frontend/packages/data-portal/app/components/Layout/Layout.tsx
Removes the Python API deprecation banner from both the docs site and the portal UI.
=> chore: Remove deprecation banner

frontend/packages/data-portal/app/graphql/getBrowseDepositionsV2.server.ts
After this change - users will also be able to put your kaggleId in the author name filter on depositions.
=> feat: Filter depositions by kaggleId or name in Author Name field

frontend/packages/data-portal/app/apiNormalization/browseAllDepositionsV2.ts, frontend/packages/data-portal/app/hooks/useDepositions.ts, frontend/packages/data-portal/app/routes/browse-data.depositions.tsx
Addresses 🐞 : https://github.com/chanzuckerberg/cryoet-data-portal/issues/1660
Deposition table was not sorting correctly when "asc" was clicked. 
This PR ensures that the `remapV2BrowseAllDepositions` function is responsive to the direction of the sorting as well as the original gql response.
=> fix: fix depositions asc sort

frontend/packages/data-portal/app/components/Deposition/DatasetsTable.tsx, frontend/packages/data-portal/app/components/Deposition/DepositionOverview.tsx, frontend/packages/data-portal/app/graphql/getDepositionByIdV2.server.ts
#1641
Fixes annotation counts for the dataset table by getting the count from `annotationsAggregate` directly
=> fix: deposition annotations count

docs/changelog.md
I updated the changelog based on information [here](https://docs.google.com/document/d/1etrUPRv_kaFAJlwDSCIuyLfxfku7185TB43zhpjXXn0/edit?usp=sharing) to address needs for #1526 .
Educational content will be added to the data organization page with #1721 to address knowledge gaps.
Once Manasa checks this for accuracy, @melissawm please merge and DO NOT backport changes as this applies to a new release of the API and does not apply to 4.0.
=> docs: Add to changelog for Frames and CTF related changes

docs/cryoet_data_portal_docsite_examples.md
Fixing access typo for s3 bucket in the example for downloading alignments. This typo will need to be backported.
=> docs: Update cryoet_data_portal_docsite_examples.md

.github/workflows/docsite-build-deploy.yml
I just realized that instead of just running the build docs job for pull requests, I was also deploying the site to the dev folder 😬 
This adds a guard to prevent the deployment if we are in a pull request.
=> fix: Fix PR preview deployments to docs site

.infra/rdev/values.yaml, frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts, frontend/packages/data-portal/app/hooks/useRunById.ts
<details open>
<summary>Argus Stack Details</summary>
<br />
<table>
<tr>
<th>App Name</th>
<td>cryoet-frontend</td>
</tr>
<tr>
<th>Stack Name</th>
<td>pet-seagull</td>
</tr>
<tr>
<th>Base URL</th>
<td><a href="https://pet-seagull.dev-cryoet.dev.czi.team" target="_blank">https://pet-seagull.dev-cryoet.dev.czi.team</a></td>
</tr>
</table>
</details>
---
#1770
Updates query for getting alignment information by filtering by alignments with non-null methods
=> fix: filter by non-null alignment method

docs/_static/js/version_redirect.js, docs/_templates/partials/header.html, docs/conf.py
Closes #1754
PREVIEW: https://melissawm.github.io/cryoet-data-portal/dev/data_model.html#data-model
To test:
- Verify that clicking on the version dropdown only opens the dropdown and doesn't navigate to the main portal page;
- Verify that for any pages/subpages, clicking on a different version in the dropdown correctly redirects to the same url, but with the selected version.
Example: navigating to
https://melissawm.github.io/cryoet-data-portal/dev/data_model.html#data-model
And clicking on the "Stable" version in the switcher should bring you to 
https://melissawm.github.io/cryoet-data-portal/v4.0/data_model.html#data-model
=> fix: Fix version switcher behavior

frontend/packages/data-portal/app/graphql/getBrowseDepositionsV2.server.ts
Ticket: [#1742](https://github.com/chanzuckerberg/cryoet-data-portal/issues/1742)
This fix means that you can now
=> fix: depositions orcid filterby

docs/Makefile, docs/_toc.yml, docs/full_changelog.md, docs/python-api.md, docs/release_notes.md
This PR adds the full changelog for the Python API client to the docs site. This is done by copying over the existing changelog file for the client into the docs sources and adding it as a new markdown page.
It also renames the current "Changelog" page to "Release notes" which is more appropriate since it contains highlights of major releases only.
=> feat: Add full changelog of Python Client to docs site

.github/workflows/docsite-build-deploy.yml
Currently, we require an update to the docs folder for the docsite to be deployed. This makes it cumbersome to update the doc-site for new client versions. 
The changes allow the doc-site to be deployed with manual trigger of the worklfow.
=> fix: Updating the workflow dispatch to deploy docsite

.github/workflows/claude-code-review.yml
This disables the claude code GitHub action temporarily until the action passes trust review. We'll re-enable it when it passes trust review.
=> ci: disable claude code review workflow

frontend/package.json, frontend/pnpm-lock.yaml
Follow-up to https://github.com/chanzuckerberg/cryoet-data-portal/pull/1955 to upgrade remaining security dependencies that were not upgraded in that PR.
This PR adds security overrides for:
- form-data: https://github.com/chanzuckerberg/cryoet-data-portal/security/dependabot/65
- path-to-regexp: https://github.com/chanzuckerberg/cryoet-data-portal/security/dependabot/38
- Added form-data@^4.0.4 override in frontend/package.json
- Added path-to-regexp@^0.1.12 override in frontend/package.json  
- Updated pnpm-lock.yaml with secure versions
=> chore: add security overrides for form-data and path-to-regexp

frontend/package.json, frontend/pnpm-lock.yaml
Temporarily removes security overrides for form-data and path-to-regexp dependencies that were recently added to resolve dependabot alerts, but are causing E2E test failures.
- Remove `form-data: ^4.0.4` security override from frontend/package.json
- Remove `path-to-regexp: ^0.1.12` security override from frontend/package.json
- Update pnpm-lock.yaml to reflect dependency changes
This is a temporary solution to unblock PRs. The long-term plan is to:
1. Restore the patched versions
2. Fix the E2E tests to work with the updated dependencies
3. Re-apply the security patches once tests are compatible
=> chore: temporarily downgrade dependencies to fix E2E tests
