client/python/cryoet_data_portal/src/cryoet_data_portal/_client.py
client/python/cryoet_data_portal/src/cryoet_data_portal/_gql_base.py
client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py
docs/cryoet_data_portal_docsite_quick_start.md

This updates the example code so that it doesn't surprise anyone with large downloads

fix: fix list relationship query filters

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_gql_base.py

fix: Fix get_by_id

---

.github/workflows/prod-deploy.yml
.github/workflows/staging-deploy.yml
frontend/.happy/terraform/envs/prod/providers.tf
frontend/.happy/terraform/envs/staging/providers.tf

Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/51

Update deployment config

---

frontend/packages/data-portal/app/components/Layout/AboutAndHelpDropdown.tsx
frontend/packages/data-portal/app/components/Layout/Footer.tsx
frontend/packages/data-portal/app/components/MDX/MdxBody.module.css
frontend/packages/data-portal/app/components/MDX/MdxBody.tsx
frontend/packages/data-portal/app/components/MDX/MdxContent.tsx
frontend/packages/data-portal/app/components/MDX/MdxEmail.tsx
frontend/packages/data-portal/app/i18n.ts
frontend/packages/data-portal/app/routes/data-submission-policy.tsx
frontend/packages/data-portal/app/utils/repo.server.ts
frontend/packages/data-portal/public/locales/en/translation.json
website-docs/data-submission-policy.mdx
website-docs/privacy-policy.mdx

as per #108 
https://github.com/chanzuckerberg/cryoet-data-portal/assets/29165011/6550ff0d-b041-462c-90a0-17d4e6bffa58

add legal docs

---

frontend/.happy/terraform/envs/dev/main.tf
frontend/.happy/terraform/envs/prod/main.tf
frontend/.happy/terraform/envs/staging/main.tf

Adding environment variable `ENV` to the task definition.

Adding ENV env var

---

website-docs/faq.mdx

Adding copy to test faq.mdx

---

frontend/packages/data-portal/app/components/AnnotatedObjectsList.tsx
frontend/packages/data-portal/app/components/BrowseData/DatasetTable.tsx
frontend/packages/data-portal/app/components/Dataset/RunsTable.tsx
frontend/packages/data-portal/app/components/Download/ConfigureDownloadContent.tsx
frontend/packages/data-portal/app/components/Download/DownloadOptionsContent.tsx
frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx
frontend/packages/data-portal/app/components/Table/TableCell.tsx
frontend/packages/data-portal/app/context/DownloadModal.context.ts
frontend/packages/data-portal/app/routes/datasets.$id.tsx
frontend/packages/data-portal/app/routes/runs.$id.tsx

addresses #231, #137
preview at https://dev-kira-misc-fixes.cryoet.dev.si.czi.technology/browse-data/datasets

fix misc bugs part 2/n

---

frontend/packages/data-portal/app/components/DatasetFilter/IncludedContentsFilterSection.tsx

Relates to: https://github.com/chanzuckerberg/cryoet-data-portal/issues/285

Adding back tomogram to filters

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py

Now that the client returns lists, let's make sure our type annotations reflect that.

Improve type hints for the client

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py

I added an alphabetic sort (a no-op) to most of the model attributes, which makes it easier to compare the docstrings to the properties of these classes.
The functional change is that I added some missing fields to the TiltSeries docstring.

Add missing documentation for TiltSeries fields.

---

.github/workflows/prod-deploy.yml
frontend/README.md

Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/438

fix: prod deploy tagging

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_client.py
client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py

Relates to https://github.com/chanzuckerberg/cryoet-data-portal/issues/480

fix: update client tomogram documentation

---

frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx
frontend/packages/data-portal/app/graphql/getRunById.server.ts

chore: hook up method type to front-end

---

frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx
frontend/packages/data-portal/app/constants/testIds.ts
frontend/packages/data-portal/e2e/config.json
frontend/packages/data-portal/e2e/filters/testMultiInputFilter.ts
frontend/packages/data-portal/e2e/filters/utils.ts
frontend/packages/data-portal/e2e/singleRunFilter.test.ts

ci: add E2E tests for single run page filters

---

client/python/cryoet_data_portal/tests/test_file_tools.py

- add test `test_dest_path_is_existing_file`
- remove unused test code.

chore: Add additional test case to TestGetDestinationPath

---

frontend/packages/data-portal/app/components/AuthorList/AuthorList.test.tsx
frontend/packages/data-portal/app/components/AuthorList/AuthorList.tsx

fix: Dedupe authors

---

frontend/packages/data-portal/app/utils/url.ts

fix: Fix Neuroglancer URL bug

---

frontend/packages/data-portal/app/components/Run/RunHeader.tsx
frontend/packages/data-portal/app/components/Run/TomogramTable.tsx
frontend/packages/data-portal/app/graphql/getRunById.server.ts
frontend/packages/data-portal/app/hooks/useRunById.ts
frontend/packages/data-portal/app/routes/runs.$id.tsx
frontend/packages/data-portal/e2e/pageObjects/singleRunPage.ts
frontend/packages/data-portal/e2e/singleRun.test.ts

closes #993
Changes query to guarantee uniqueness and order.

feat: Update Tomogram Processing field format and query

---

frontend/packages/data-portal/app/apollo.server.ts

fix: Disable Apollo Client cache on the server

---

frontend/packages/data-portal/app/components/Run/TomogramTable.tsx
frontend/packages/data-portal/app/components/TablePageLayout.tsx
frontend/packages/data-portal/app/constants/table.ts
frontend/packages/data-portal/app/graphql/getRunById.server.ts
frontend/packages/data-portal/app/utils/tomograms.ts
frontend/packages/data-portal/public/locales/en/translation.json

feat: More updates to tomograms table

---

frontend/packages/data-portal/app/components/Download/ConfigureDownloadContent.tsx
frontend/packages/data-portal/app/components/Download/ConfigureTomogramDownloadContent.tsx
frontend/packages/data-portal/app/components/Download/DownloadOptionsContent.tsx
frontend/packages/data-portal/app/components/Download/FileFormatDropdown.tsx
frontend/packages/data-portal/app/components/Download/TomogramSelectorLabel.tsx
frontend/packages/data-portal/app/components/Download/TomogramSelectorOption.tsx
frontend/packages/data-portal/app/components/Radio/Radio.tsx
frontend/packages/data-portal/app/components/Run/RunHeader.tsx
frontend/packages/data-portal/app/components/Run/TomogramTable.tsx
frontend/packages/data-portal/app/components/Select.tsx
frontend/packages/data-portal/app/constants/query.ts
frontend/packages/data-portal/app/hooks/useDownloadModalQueryParamState.ts
frontend/packages/data-portal/app/hooks/usePlausible.ts
frontend/packages/data-portal/app/routes/runs.$id.tsx
frontend/packages/data-portal/e2e/downloadDialog.test.ts
frontend/packages/data-portal/e2e/pageObjects/downloadDialog/downloadDialogActor.ts
frontend/packages/data-portal/e2e/pageObjects/downloadDialog/downloadDialogPage.ts
frontend/packages/data-portal/e2e/pageObjects/downloadDialog/utils.ts
frontend/packages/data-portal/playwright.config.ts
frontend/packages/data-portal/public/locales/en/translation.json

#1005 
Does not include changes dependent on `tomogram.is_portal_standard` and `tomogram.is_author_submitted`.
Fixes bug where `<Select>` doesn't close when selecting the already selected option.

feat: Implement new single tomogram download flow

---

docs/_static/css/custom.css

Changes styling of page, text link and code snippets. Accordion styling is not yet addressed.

docs: Implement SDS colors for dark mode

---

frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts

The field's name is being changed.

feat: Stop querying publications in V2 temporarily

---

frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
frontend/packages/data-portal/codegen.ts

feat: Add more V2 API fields

---

docs/_static/css/custom.css
docs/_templates/partials/footer.html
docs/_templates/partials/header.html
docs/_toc.yml

docs: Fix footer colors and header and footer links

---

.github/workflows/formatting.yml
docs/_static/css/custom.css

And starts running precommit on changes to static since it runs on that folder.

fix: Fix lint issue in static

---

frontend/packages/data-portal/app/apollo.server.ts
frontend/packages/data-portal/app/components/Run/RunHeader.tsx
frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
frontend/packages/data-portal/app/hooks/useRunById.ts
frontend/packages/data-portal/e2e/apollo.ts

#1101 
Also temporarily disables automatic querying of `__typename` due to a bug in the new API.

feat: Integrate more V2 API queries

---

frontend/packages/data-portal/app/components/Download/Tomogram/TomogramSelectorLabel.tsx
frontend/packages/data-portal/app/components/Download/Tomogram/TomogramSelectorOption.tsx
frontend/packages/data-portal/app/components/Run/TomogramTable.tsx
frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts

tomogram.isStandardized -> tomogram.isPortalStandard
NOTE: we should decide how/when we want to deploy this fix.

fix: support changed field name

---

docs/cryoet_data_portal_docsite_data.md

Adding updated figure for the run download folder structure

Update run download folder structure

---

docs/cryoet_data_portal_docsite_faq.md
docs/neuroglancer_quickstart.md

- Increasing image size and adding link to additional documentation in the quick start guide
- Updating the FAQ to reference our documentation

Update Neuroglancer docs and references

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_codegen.py
client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py
client/python/cryoet_data_portal/tests/test_alignments.py

An alternative fix for #1343 that includes updates to the codegen so we don't lose these changes next time we update the schema.

fix: Fixes for relationship field naming.

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_client.py
client/python/cryoet_data_portal/tests/test_get_client.py

This PR adds the ability for a Client object to be shared between threads. Initially, we created one HTTPTransport object that was used for the lifetime of a Client. These transports are not thread safe and can't handle concurrent access!
This PR creates a single Schema object when a Client is instantiated (this takes ~1/10s so we want to minimize how often we redo this work) and then creates a new Transport for each request, using the Schema object we created earlier. Since each request has its own Transport, it's no longer possible for multiple threads to attempt concurrent access to a Transport.

feat: Support a Client object being shared between threads.

---

client/python/cryoet_data_portal/tests/test_get_client.py

Starting to improve the thread safety tests

chore: Make threading tests more concise.

---

frontend/packages/data-portal/app/utils/apiMigration.test.ts
frontend/packages/data-portal/app/utils/apiMigration.ts

feat: api migration setup

---

docs/_toc.yml
docs/about.md
docs/cryoet_data_portal_docsite_faq.md
docs/cryoet_data_portal_docsite_napari.md
docs/cryoet_data_portal_docsite_quick_start.md
docs/neuroglancer_quickstart.md
docs/tutorials.md

docs: Surface neuroglancer quickstart

---

.github/workflows/docsite-build-deploy.yml

Closes https://github.com/chanzuckerberg/cryoet-data-portal/issues/1388

chore: Automate docs site deployment

---

.github/workflows/client-python.yml
client/python/cryoet_data_portal/tests/test_infra/get_deployment.sh
docs/cryoet_data_portal_docsite_quick_start.md

- Updated test matrix - removed Python 3.7 and added 3.11 and 3.12
- Fixed `coverage`

chore: update python matrix

---

frontend/packages/data-portal/app/graphql/getRunById.server.ts
frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts

Also update printed value to just be the actual objects (much easier to plug the 2 strings into an online JSON differ and see all the fields to get a sense of what's different).

fix: Fix run query diff logging

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py
client/python/cryoet_data_portal/src/cryoet_data_portal/data/schema.graphql

Relates to: https://github.com/chanzuckerberg/cryoet-data-portal-backend/pull/387

feat: add size fields to TiltSeries

---

frontend/packages/data-portal/app/graphql/getDatasetById.server.ts
frontend/packages/data-portal/app/graphql/getDatasetByIdV2.server.ts
frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
frontend/packages/data-portal/app/hooks/useDatasetById.ts
frontend/packages/data-portal/app/routes/datasets.$id.tsx
frontend/packages/data-portal/codegen.ts

Also switch GQL codegen schema back to prod, now that prod seems stable.
Next: Add diff logging for this query.

feat: Add V2 query for dataset page

---

frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts
frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
frontend/packages/data-portal/app/hooks/useRunById.ts

Also start using V2 `depositions` field.

feat: Finish converting run page query to V2

---

frontend/packages/data-portal/app/hooks/useDatasetById.ts

Can't start using V2 fields for the runs table yet (at least in staging), since there is a bug in the staging data https://czi-sci.slack.com/archives/C07DNE66ZS9/p1734717874962739

feat: Use some V2 fields in dataset page

---

frontend/packages/data-portal/app/graphql/getDepositionByIdV2.server.ts

The last deploy failed, but the release please PR was merged.

feat: Dummy PR to trigger release please

---

frontend/packages/data-portal/app/graphql/getDepositionByIdV2.server.ts

I changed the wrong branch's protection rule so the same thing happened, release please PR was merged but deploy failed due to branch protection rule (I'm deploying from a custom branch that skips e2e staging tests because a data inconsistency between V1 and V2 is causing a test to fail and block the release).

feat: Another dummy PR

---

frontend/packages/data-portal/app/graphql/common.ts

feat: Add aggregate filters to datasets and deposition queries

---

frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts

fix: Run page differ fixes to handle BE edge cases/bugs

---

frontend/packages/data-portal/app/components/Run/TomogramMetadataDrawer.tsx
frontend/packages/data-portal/app/components/Run/TomogramTable.tsx

fix: Remove time zones from tomogram date fields

---

frontend/packages/data-portal/app/graphql/getDatasetByIdDiffer.ts
frontend/packages/data-portal/app/graphql/getDatasetsDiffer.ts
frontend/packages/data-portal/app/graphql/getDepositionDiffer.ts
frontend/packages/data-portal/app/graphql/getRunByIdDiffer.ts

I'm using `happy logs` which doesn't include timestamps 😢

feat: Add timestamps to diff logs

---

frontend/packages/data-portal/app/components/BrowseData/DatasetTable.tsx
frontend/packages/data-portal/app/hooks/useDatasets.ts
frontend/packages/data-portal/app/types/gql/datasetsPageTypes.ts

closes #1228
Very similar to #1549

feat: Complete migration of datasets page to V2

---

index.html
python-api.html

Sorry, silly typo. cc @rainandbare

fix: Typo in gh-pages redirect

---

frontend/packages/data-portal/app/components/Layout/Layout.tsx

This should go to prod on 1/30.

feat: Take down ML Challenge banner

---

frontend/packages/data-portal/app/components/Radio/Radio.tsx

fix: Add hover state for Download radio buttons

---

frontend/packages/data-portal/app/components/BrowseData/BrowseDataTabs.tsx
frontend/packages/data-portal/app/components/Index/IndexHeader.tsx
frontend/packages/data-portal/app/routes/_index.tsx
frontend/packages/data-portal/app/routes/browse-data.tsx
frontend/packages/data-portal/codegen.ts

closes #1573
And simplify some code.

feat: Migrate other misc queries

---

frontend/packages/data-portal/app/apiNormalization/browseAllDepositionsV1.ts
frontend/packages/data-portal/app/apiNormalization/browseAllDepositionsV2.ts
frontend/packages/data-portal/app/components/BrowseData/DepositionTable.tsx
frontend/packages/data-portal/app/graphql/getBrowseDepositionsV2.server.ts
frontend/packages/data-portal/app/hooks/useDepositions.ts
frontend/packages/data-portal/app/types/PageData/browseAllDepositionsPageData.ts

feat: Migrate missing field from depositions query

---

frontend/packages/data-portal/app/components/AuthorLink/AuthorLink.test.tsx
frontend/packages/data-portal/app/components/AuthorLink/types.ts
frontend/packages/data-portal/app/components/AuthorList/AuthorList.test.tsx
frontend/packages/data-portal/app/components/AuthorList/AuthorList.tsx
frontend/packages/data-portal/app/components/Dataset/DatasetMetadataTable.tsx
frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx
frontend/packages/data-portal/app/components/Run/RunHeader.tsx
frontend/packages/data-portal/app/components/Run/RunMetadataDrawer.tsx
frontend/packages/data-portal/app/components/Run/RunTiltSeriesTable.tsx
frontend/packages/data-portal/app/components/Run/TomogramMetadataDrawer.tsx
frontend/packages/data-portal/app/components/Run/TomogramTable.tsx
frontend/packages/data-portal/app/components/TiltSeriesTable/useTiltSeriesValueMappings.tsx
frontend/packages/data-portal/app/context/DownloadModal.context.ts
frontend/packages/data-portal/app/hooks/useRunById.ts
frontend/packages/data-portal/app/routes/runs.$id.tsx
frontend/packages/data-portal/app/types/gql/genericTypes.ts
frontend/packages/data-portal/app/utils/tiltSeries.ts

closes #636
closes #1232
Also switches from using subtraction to calculate the tilt range to using the GraphQL field to avoid floating point errors.

feat: Finish run page migration to V2

---

frontend/packages/data-portal/app/components/ViewTomogramButton.tsx

New (old) font is slightly bigger, needs more space.

fix: Runs table View Tomogram button styling

---

docs/changelog.md
docs/conf.py

cc @dgmccart 
I will need to follow up with a (quick) gh-pages update following this PR.

docs: Fix changelog, bump stable version

---

frontend/packages/data-portal/app/components/Deposition/DepositionOverview.tsx
frontend/packages/data-portal/app/components/Layout/TopNavigation.tsx
frontend/packages/data-portal/app/components/Layout/constants.ts
frontend/packages/data-portal/app/components/MLChallenge/CompletedMLChallenge/components/CompletedChallengeLayout/CompletedChallengeLayout.tsx
frontend/packages/data-portal/app/components/MLChallenge/CompletedMLChallenge/components/WinnerCard/WinnerCard.tsx
frontend/packages/data-portal/app/components/MLChallenge/CompletedMLChallenge/constants.ts
frontend/packages/data-portal/app/constants/tags.ts
frontend/packages/data-portal/app/graphql/getWinningDepositionsV2.server.ts
frontend/packages/data-portal/app/utils/featureFlags.ts

Removes the dummy queries and promotes the postMlChallenge query to staging.

feat: Prepare code for real kaggle id and tag data

---

frontend/packages/data-portal/app/components/Run/AnnotationTable.tsx
frontend/packages/data-portal/app/graphql/getBrowseDepositionsV2.server.ts

fixes: https://github.com/chanzuckerberg/cryoet-data-portal/issues/1661

fix: Add run specific ids to annotation table

---

frontend/packages/data-portal/app/components/I18n.tsx
frontend/packages/data-portal/app/utils/featureFlags.ts

feat: Promote Post ML competition page to prod

---

.github/workflows/argus-stack-prod-upsert.yaml
.github/workflows/argus-stack-rdev-create.yaml
.github/workflows/argus-stack-rdev-delete.yaml
.github/workflows/argus-stack-staging-upsert.yaml
.infra/rdev/values.yaml
frontend/packages/data-portal/Dockerfile
frontend/packages/data-portal/README.md

<details open>
<summary>Argus Stack Details</summary>
<br />
<table>
<tr>
<th>App Name</th>
<td>cryoet-frontend</td>
</tr>
<tr>
<th>Stack Name</th>
<td>allowing-airedale</td>
</tr>
<tr>
<th>Base URL</th>
<td><a href="https://allowing-airedale.dev-cryoet.dev.czi.team" target="_blank">https://allowing-airedale.dev-cryoet.dev.czi.team</a></td>
</tr>
</table>
</details>
---

fix: update docker

---

.infra/prod/values.yaml
.infra/rdev/values.yaml
.infra/staging/values.yaml
frontend/README.md

<details open>
<summary>Argus Stack Details</summary>
<br />
<table>
<tr>
<th>App Name</th>
<td>cryoet-frontend</td>
</tr>
<tr>
<th>Stack Name</th>
<td>prepared-fox</td>
</tr>
<tr>
<th>Base URL</th>
<td><a href="https://prepared-fox.dev-cryoet.dev.czi.team" target="_blank">https://prepared-fox.dev-cryoet.dev.czi.team</a></td>
</tr>
</table>
</details>
---

fix: env var

---

docs/cryoet_data_portal_docsite_data.md

Adding location for hyperlinking regarding ground truth

docs: Add ground truth section to data organization page

---

.infra/rdev/values.yaml
frontend/packages/data-portal/app/components/Layout/AboutAndReportDropdown.tsx
frontend/packages/data-portal/app/components/Layout/MobileNavigationMenu.tsx
frontend/packages/data-portal/app/components/Layout/TopNavigation.tsx
frontend/packages/data-portal/app/components/Layout/constants.ts
frontend/packages/data-portal/app/constants/siteLinks.ts
frontend/packages/data-portal/public/locales/en/translation.json

<details open>
<summary>Argus Stack Details</summary>
<br />
<table>
<tr>
<th>App Name</th>
<td>cryoet-frontend</td>
</tr>
<tr>
<th>Stack Name</th>
<td>superb-kodiak</td>
</tr>
<tr>
<th>Base URL</th>
<td><a href="https://superb-kodiak.dev-cryoet.dev.czi.team" target="_blank">https://superb-kodiak.dev-cryoet.dev.czi.team</a></td>
</tr>
</table>
</details>
---
Github Issue: #1678

feat: update top nav

---

frontend/packages/data-portal/app/components/Index/IndexCTA.tsx
frontend/packages/data-portal/public/locales/en/translation.json

feat: swap text on front page

---

.infra/rdev/values.yaml
docs/cryoet_data_portal_docsite_data.md
frontend/packages/data-portal/app/components/Layout/Footer.tsx
frontend/packages/data-portal/app/i18n.ts

Github Issue: #1698
@kandarpksk Can you check that these are the correct links? Including hidden event values.

feat: add links in footer

---

frontend/packages/data-portal/public/locales/en/translation.json

Fixing my fix - I forgot to add the word "in" 🤦‍♀️

fix: Add the word in!

---

docs/changelog.md
docs/cryoet_data_portal_docsite_aws.md
docs/cryoet_data_portal_docsite_data.md
docs/cryoet_data_portal_docsite_examples.md
docs/cryoet_data_portal_docsite_faq.md
docs/cryoet_data_portal_docsite_landing.md
docs/cryoet_data_portal_docsite_quick_start.md
docs/data_model.md

- Landing page: Updated tomogram count  and improving citation phrasing
- Quickstart: Added examples of using find, anchors, and fixed broken code snippets
- FAQ: Updated outdated questions and fixed broken code snippets
- Download Data with AWS: Updated code snippets for v4 API
- Changelog: Updated warning about API deprecation
- Data Organization: Improved phrasing + Added sections for additional data entities (e.g. tomograms, tilt series, etc)

docs: Doc improvements following audit + expansion of data organization page

---

.github/workflows/docsite-build-deploy.yml
.github/workflows/formatting.yml
docs/cryoet_data_portal_docsite_data.md
docs/requirements.txt

Also fixes previously flagged trailing whitespace in docs.
Closes #1732

chore: Add pre-commit checks to docs builds

---

docs/_static/css/custom.css

fix: Remove box-shadow from FAQ elements

---

docs/cryoet_data_portal_docsite_examples.md

docs: Add anchors to Examples in docs site

---

frontend/packages/data-portal/app/components/Dataset/DatasetOverview.tsx

Fixes issue [#1773](https://github.com/chanzuckerberg/cryoet-data-portal/issues/1773)

fix: add min width to descriptions 

---

.github/workflows/release-please.yml

This is an AI generated PR.
Execution time: 24471 ms
Cost: $0.06

chore: CCIE-4313 replace tibdex/github-app-token

---

docs/README.md
docs/conf.py

Closes #1777
Also addresses #1799

docs: Add documentation on deployment and versioning of docs site

---

frontend/packages/data-portal/app/constants/siteLinks.ts

chore: Fix URL in Learn More link for Ground Truth

---

client/python/cryoet_data_portal/src/cryoet_data_portal/_models.py
client/python/cryoet_data_portal/src/cryoet_data_portal/data/schema.graphql

chore: Fix typo in AnnotationFile API documentation

---

frontend/packages/data-portal/app/i18n.ts
frontend/packages/data-portal/public/locales/en/translation.json

chore: Update author filter wording to ORCID ID

---

docs/cryoet_workflow.md

chore: Fix typo in DenoisET and add link

---

.github/workflows/claude-code-review.yml

fixes #1931 and actually disables the action. the previous PR only disable the event filter so it was causing the claude code action to always run for every PR event.
this is what happens when I don't let claude code write code for me 😆 😭

fix: claude code action

---

docs/_static/css/custom.css
docs/_toc.yml
docs/about.md
docs/contributing_data.md
docs/cryoet_data_portal_docsite_data.md
docs/cryoet_data_portal_docsite_faq.md
docs/cryoet_data_portal_docsite_landing.md

Also includes some styling changes to wrap text in secondary (in-page) sidebar.
Closes #1605 
Closes #1874

docs: Add article about data contribution process

---

docs/contributing_data.md

chore: Add links to examples in data contribution page
